
# Licensed under GNU Lesser General Public License v3.0

# install: conda env create -f conda_env.yaml 
# update:  conda env update -f conda_env.yaml 

name: noexiit
dependencies:
  - python=3.8
  - pip
  - pyyaml
  - numpy
  - pandas
  - matplotlib
  - scipy
  - requests
  - pyserial
  - pyyaml
  - tqdm
  - click
  - pip:
    - -r requirements.txt