calibrate:
  max_ext: 180.0
  output_dir: /mnt/more_vids/
  
expt-pt-to-pt:
  duration: 20 # secs
  ext_wait_time: 2 # secs
  extension: 90
  poke_speed: 10
  positions:
  - 180
  - 0
  retr_wait_time: 2

expt-still-robot:
  duration: 30 # secs
  k_stepper: 1
  ball_radius: 5 # mm
  fictrac_exe_path: ~/src/fictrac_noexiit/bin/fictrac
  fictrac_config_path: ~/src/fictrac_noexiit/my_scripts/config_c_loop.txt

sniff-and-puff:

  duration: null
  output_dir: null

  port: /dev/ttyACM1
  pre_stim_durn: 2
  stim_durn: 2
  post_stim_durn: 2
  on_valve_id: 1
  off_valve_id: 0
  